"""Browser-independent worker contract. Engine objects never cross the worker boundary."""

from typing import Protocol


class BrowserAdapter(Protocol):
    def open(self, session_id: str, url: str | None, new_tab: bool) -> dict: ...
    def list_tabs(self, session_id: str) -> dict: ...
    def navigate(self, session_id: str, tab_id: str, operation: str, url: str | None) -> dict: ...
    def observe(self, session_id: str, tab_id: str, **options) -> dict: ...
    def prepare(
        self, session_id: str, tab_id: str, expected_revision: int, action: dict
    ) -> dict: ...
    def act(self, session_id: str, tab_id: str, expected_revision: int, action: dict) -> dict: ...
    def configure(self, session_id: str, tab_id: str, options: dict) -> dict: ...
    def close(self, session_id: str, scope: str, tab_id: str | None) -> dict: ...
    def resume(self, session_id: str, tab_id: str) -> dict: ...
    def focus(self, session_id: str, tab_id: str) -> dict: ...
    def shutdown(self) -> None: ...
